# Generated by Django 4.1.6 on 2023-02-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
